### ISSUE TITLE
dead video link

### ISSUE THREAD

**Issue by eczajk1** [jflasher/reinvent-geospatial#2]
FYI, the video link for the [Global Open Transportation Projects](https://github.com/jflasher/reinvent-geospatial/blob/master/2018-ps-summit.md#global-open-transportation-projects) session is dead (2018 DC Public Sector Summit). I could not find it on YouTube either.

Thanks for posting these.

**Comment by jflasher** [comment]
Hi @eczajk1, thanks for pointing this out. Unfortunately there were some issues with the slide formatting and we won't be sharing the video or slides for this presentation. I've removed the dead links. Thanks!
